Smartcamp_type
camptocamp/odoo-platform-charts pull request #40
Opened 2022-10-24 11:39 UTC by nbessi

2022-10-24 12:34 UTC, p-tombez requested changes
LGTM, just a tiny bit of indent
Also, needs a rebase

2022-10-24 12:34 UTC, p-tombez commented on odoo/templates/_helpers.tpl
> +  {{- else if eq .Values.odoo.instance_type "smartcamp" -}}
Wrong indent

2022-11-10 10:41 UTC, p-tombez approved these changes

2022-11-10 11:02 UTC, vrenaville approved these changes

2023-12-19 14:58 UTC, merged